require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "node_modules/**/*"
  TargetRubyVersion: 3.0.0

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Rails/SkipsModelValidations:
  Enabled: false
